version: '2'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:cached
      - ./:/app
    ports:
      - '8000:80'

  node:
      image: node:16
      working_dir: /app
      volumes:
          - ./:/app:cached

  mysql:
    image: mysql/mysql-server:8.0
    environment:
        MYSQL_DATABASE: fundraiser
        MYSQL_ROOT_PASSWORD: fundraiser
        MYSQL_ROOT_HOST: '%'
    volumes:
      - db-data:/var/lib/mysql

volumes:
    db-data:
